### PR TITLE
Adds Bazel Support

### PR DESCRIPTION
**Pull request by tinder-maxwellelliott**
Adds Bazel Support to GitQuery

### CODE REVIEW

**Review by tinder-aminghadersohi — APPROVED** [review]

**Comment by tinder-aminghadersohi** [comment]
this is amazing!

**Comment by tinder-aminghadersohi** [comment]
@tinder-maxwellelliott what do we need to do to release this?

**Comment by tinder-maxwellelliott** [comment]
> @tinder-maxwellelliott what do we need to do to release this?

Nothing really, I can expand on how to actually consume it, but people using Bazel should be able to adopt this. If you want we could also create deployable JARs now via Bazel

**Comment by tinder-aminghadersohi** [comment]
> > @tinder-maxwellelliott what do we need to do to release this?
> 
> Nothing really, I can expand on how to actually consume it, but people using Bazel should be able to adopt this. If you want we could also create deployable JARs now via Bazel

Nice! No need to do extra work if we don’t need.

**Comment by tinder-maxwellelliott** [comment]
@aminghadersohi This is ready to land

**Comment by Psoffie009** [comment]
> [CLA assistant check](https://cla-assistant.io/Tinder/GitQuery?pullRequest=57)
> All committers have signed the CLA.

**Comment by Psoffie009** [comment]
> @aminghadersohi This is ready to land

**Pull request merged**
