### PR TITLE
release 3.0.9

### PR DESCRIPTION
**Pull request by tinder-aminghadersohi**
Renamed BUILD to BUILD.bazel
https://github.com/bazelbuild/bazel/issues/4517

### CODE REVIEW

**Comment by tinder-aminghadersohi** [comment]
build samples will at first fail, its normal. i have to do a release manually and then rebuild here. Waiting for @tinder-maxwellelliott to give final ok

**Comment by tinder-maxwellelliott** [comment]
LGTM!!!

**Comment by tinder-aminghadersohi** [comment]
just did the release. it usually takes a few minutes to propagate the artifact after which i will retry the `build_samples` circle task and merge

**Comment by Psoffie009** [comment]
> Renamed BUILD to BUILD.bazel
> [bazelbuild/bazel#4517](https://github.com/bazelbuild/bazel/issues/4517)

**Comment by Psoffie009** [comment]
> just did the release. it usually takes a few minutes to propagate the artifact after which i will retry the `build_samples` circle task and merge

**Comment by Psoffie009** [comment]
> LGTM!!!

**Pull request merged**
